version: '3.8'
services:
  redis:
    image: redis
    hostname: redis
    env_file:
    - terraform.tfvars
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 6
  s3jobproducer:
    build:
      context: ./
      target: s3Producer
    image: s3jobproducer
    command: ["node", "s3JobProducer.js"]
    hostname: s3jobproducer
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    hostname: s3jobproducer
    env_file:
    - terraform.tfvars
  s3jobconsumer:
    build:
      context: ./
      target: s3Consumer
    image: s3jobconsumer
    command: ["node", "s3JobConsumer.js"]
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
      - s3jobproducer
    deploy:
      replicas: 1
    hostname: s3jobconsumer
    env_file:
    - terraform.tfvars
