version: '3.8'

volumes:
  redis-raft:

services:
  redis:
    image: redis
    hostname: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 6
    volumes:
     - redis-raft:/data
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
  s3jobproducer:
    build:
      context: ./
      target: s3Producer
    image: s3jobproducer
    command: ["node", "s3JobProducer.js"]
    hostname: s3jobproducer
    healthcheck:
      test: ["CMD", "ping", "localhost","-c","1"]
      interval: 10s
      timeout: 3s
      retries: 6
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    hostname: s3jobproducer
  s3jobconsumer:
    build:
      context: ./
      target: s3Consumer
    image: s3jobconsumer
    command: ["node", "s3JobConsumer.js"]
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
      - s3jobproducer
    deploy:
      replicas: 1
    hostname: s3jobconsumer
